In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
type(my_matrix)

list

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [26]:
len(np.linspace(0,5,21))

21

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [156]:
np.random.rand(1)

array([0.72900717])

In [33]:
np.random.rand(5,2)

array([[0.18466115, 0.16150585],
       [0.3731144 , 0.70316145],
       [0.72401946, 0.18281303],
       [0.81893065, 0.00155934],
       [0.17619871, 0.82079938]])

In [34]:
np.random.randn(10)

array([ 0.50545474, -0.59555156, -0.75681837, -0.85399682, -0.38187694,
        0.12059416, -1.73228574,  0.20190913, -1.75269607, -0.79983607])

In [36]:
np.random.randn(2,3)

array([[-1.02728056, -0.3436261 , -0.14670189],
       [-2.36902671,  0.02215691, -0.23939539]])

In [38]:
np.random.randint(0,101,5)

array([ 7,  6, 18, 68, 66])

In [39]:
np.random.randint(0,101,(4,5))

array([[16, 93, 95, 23, 19],
       [33, 65, 10, 17,  3],
       [81, 40, 42, 35, 57],
       [54, 85, 62, 29, 59]])

In [40]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [41]:
arr = np.arange(0,25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
ranarr = np.random.randint(0,101,10)

In [49]:
ranarr

array([44, 64, 88, 70,  8, 87,  0,  7, 87, 62])

In [50]:
ranarr.max()

88

In [51]:
ranarr.min()

0

In [52]:
ranarr.argmax()

2

In [53]:
ranarr.argmin()

6

In [54]:
ranarr.dtype

dtype('int64')

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
arr.shape

(25,)

In [67]:
arr = arr.reshape(5,5)

In [68]:
arr.shape

(5, 5)

In [69]:
abb = np.arange(0,11)

In [70]:
abb

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
abb[8]

8

In [75]:
abb[1:5]

array([1, 2, 3, 4])

In [77]:
abb[:5]

array([0, 1, 2, 3, 4])

In [79]:
abb[5:]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
abb

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
abb[0:5] = 100

In [83]:
abb

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [85]:
app = np.arange(0,11)

In [88]:
slice_of_app = app[0:5]

In [89]:
slice_of_app

array([0, 1, 2, 3, 4])

In [90]:
app

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
slice_of_app[:] = 99

In [92]:
slice_of_app

array([99, 99, 99, 99, 99])

In [93]:
app_copy = app.copy()

In [95]:
app_copy[:] =100

In [98]:
app_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [100]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [101]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [102]:
arr_2d.shape

(3, 3)

In [103]:
arr_2d[0]

array([ 5, 10, 15])

In [105]:
arr_2d[1][1]

25

In [106]:
arr_2d[1,1]

25

In [107]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [108]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [109]:
abc = np.arange(1,11)

In [110]:
abc

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
abc > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [117]:
bool_abc = abc>4

In [114]:
bool_abc 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [118]:
abc[bool_abc]

array([ 5,  6,  7,  8,  9, 10])

In [119]:
abc[abc>4]

array([ 5,  6,  7,  8,  9, 10])

In [120]:
lzc =  np.arange(0,10)

In [121]:
lzc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
lzc + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
lzc - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [125]:
lzc + lzc

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [126]:
lzc * lzc

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [128]:
lzc - lzc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [129]:
lzc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
lzc/lzc

/var/folders/zx/s45q4xb93tdfqjjntxnk_k3w0000gn/T/ipykernel_20304/1699748600.py:1: RuntimeWarning: invalid value encountered in true_divide
  lzc/lzc


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [132]:
1/0

ZeroDivisionError: division by zero

In [133]:
1/arr

/var/folders/zx/s45q4xb93tdfqjjntxnk_k3w0000gn/T/ipykernel_20304/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([[       inf, 1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158],
       [0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667]])

In [134]:
np.sqrt(lzc)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [135]:
np.sin(lzc)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [136]:
np.log(lzc)

/var/folders/zx/s45q4xb93tdfqjjntxnk_k3w0000gn/T/ipykernel_20304/1570613051.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(lzc)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [137]:
 lzc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
lzc.sum()

45

In [139]:
lzc.mean()

4.5

In [140]:
lzc.var()

8.25

In [142]:
lzc.std()

2.8722813232690143

In [143]:
lzc.max()

9

In [148]:
lzc2d = np.arange(0,25).reshape(5,5)

In [149]:
lzc2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [150]:
lzc2d.sum()

300

In [153]:
lzc2d.sum(axis = 0)#cross rows

array([50, 55, 60, 65, 70])

In [154]:
lzc2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])